#!/bin/bash

echo "For details see 
$0
"

helpfulCommands () {
echo "
Bash Aliases
  $ alias

Configuration Information
  $ codoc

X Session Management
  $ startx     # Start the x server
  $ killx      # Kill the x server

Network Control
  $ wifi.sh    # Connect to wifi (under development)
"
	return
}

softwareManagement () {
echo "
Searching for Software
  $ xbps-query -Rs <package name>

Installing Software
  $ sudo xbps-install -S <package name>

Updating a single package
  $ sudo xbps-install -Su <package name>

Updating All Software
  $ sudo xbps-install -Su
"
	return
}

dwmShortcuts () {
echo "
  <alt>j,k           Switch terminals
  <alt>h,l           move terminal split
  <alt><shift>ENTER  open new terminal
  <alt>ENTER         swap window with main
  <shift><alt>q      exit DWM
                 $ pkill -KILL -u $USER
  <alt>1-0 -- switch desktops
  <alt>p -- run dmenu
  <alt>m -- toggle monocle layout
  <alt>SPACE -- toggle recent layout(s)
  <alt>t -- tiled layout
  <alt>m --  full-screen layout
"
}

startxsession () {
	startx
	return
}

exec-xbps-update () {
	sudo xbps-install -Su
}

mount-usb () {
        bashmount
}

PS3='Please enter your choice: '
options=(
	"Start X session" \
	"Helpful Commands" \
	"Software Management" \
	"DWM Shortcuts" \
	"exec update"\
	"mount usb"\
	"Quit")
select opt in "${options[@]}"
do
	case $opt in
		"Start X session")
			echo $opt
			startxsession
			break
			;;
		"Helpful Commands")
			echo $opt
			helpfulCommands
			break
			;;
		"Software Management")
			echo $opt
			softwareManagement
			break
			;;
		"DWM Shortcuts")
			echo $opt
			dwmShortcuts
			break
			;;
		"exec update")
			exec-xbps-update
			break
			;;
		"mount usb")
			mount-usb
			break
			;;
		"Quit")
			break
			;;
		*) echo "invalid $REPLY";;
	esac
done
