#
# ~/.bash_profile
#

# test of .bashrc exists. If so, load run it
[[ -f ~/.bashrc ]] && . ~/.bashrc

if [ -n "$TMUX" ]
then
	:
else
# TODO wait for user input to start X org or continue to shell
	#startx # start the xserver and execute .xinitrc
	echo "Type 'startx' to start the X server"
fi


