# This file is ~/.bashrc

# TODO Increase .bash_history size
# TODO add description to .bashrc
# TODO move alias prt to script in void/local/scripts
# TODO in bashrc, set a GIT_DIRECTORY environment variable

export VISUAL=vim
export EDITOR="${VISUAL}"
# Key bindings ################################################################

# CODOC <CTRL>f             run tmuxer
bind -x '"\C-f":"tmuxer"' # ~/.local/scripts/tmuxer

# CODOC <CTRL>h             copy line from bash_history to clipboard via fzf
bind -x '"\C-h":"cat ~/.bash_history | \
	fzf --scheme history | head -c -1 | \
	xsel --clipboard"'

# Command Aliases #############################################################
# command: prt
# description: Print text file to default printer.
# usage: prt <file>
# CODOC prt                 print a document
alias prt='lp -o media=a4 -o cpi=12 -o lpi=7.2 -o page-left=48 \
	-o page-right=48 -o page-top=48 -o page-bottom=48 < '

# give some default flags to ls
# command: ll
# description: Give some default flags to ls.
#              -G    in long listing, don't print group names
#              -F    append indicator (one of */=>@|) to entries
#              -h    print human-readable file sizes
# usage: ll
# CODOC ll                  alias ll='ls -GFh'
alias ll='ls -GFh'

# Make common commands use color
alias diff='diff --color'
alias grep='grep --color'
alias ls='ls --color'

# command dmesg
# description: Make dmesg better
# usage: dmesg
# CODOC dmesg               alias dmesg='dmesg -wH'
alias dmesg='dmesg -wH'

# command: weather
# description: Get weather reports
# usage: weather
# CODOC weather             display weather report
alias weather='curl wttr.in/?n?p?2'

# command: bc
# description: Improved bc calculator
# usage: bc
# CODOC bc                  alias='bc -lq'
alias bc='bc -lq'

# COLORS ######################################################################

# Define Colors


# Reset Colors
Color_Off='\[\033[0m\]'

# Set colors for Linux term (Crlt+Shift+Fn)
if [ "$TERM" == "linux" ]; then
	echo ""
else
    echo -en "\e]P1c1c1c" #black
    echo -en "\e]P767676" #darkgrey
    echo -en "\e]Paf5f5f" #darkred
    echo -en "\e]Pd75f87" #red
    echo -en "\e]P5faf5f" #darkgreen
    echo -en "\e]P87d787" #green
    echo -en "\e]Paf875f" #darkyellow
    echo -en "\e]Pd7af87" #yellow
    echo -en "\e]P5f87af" #darkblue
    echo -en "\e]P5fafd7" #blue
    echo -en "\e]Paf87af" #darkmagenta
    echo -en "\e]Pd787d7" #magenta
    echo -en "\e]P5f8787" #darkcyan
    echo -en "\e]P87afaf" #cyan
    echo -en "\e]P9e9e9e" #lightgrey
    echo -en "\e]Pc7c7c7" #white
    clear #for background artifacting
fi

export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
#export CLICOLOR=1
#export LSCOLORS=GxFxCxDxBxegedabagaced


# PATH Variable ###############################################################
export PATH='' # clear PATH variable

export PATH=$PATH:/bin
export PATH=$PATH:/sbin

export PATH=$PATH:/opt/local/bin
export PATH=$PATH:/opt/local/sbin

export PATH=$PATH:/usr/bin
export PATH=$PATH:/usr/sbin
export PATH=$PATH:/usr/games

export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:/usr/local/games

export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.local/bin/
export PATH=$PATH:$HOME/.local/scripts/
