#!/usr/bin/env bash

CODOC_CONFIG_VERSION=1

# Notes #######################################################################

# Codoc Directories List ######################################################
CODOC_DIRS+=("${HOME}/.config/")
CODOC_DIRS+=("${HOME}/.local/scripts/")

# Codoc File List #############################################################
CODOCS["bashrc"]="${HOME}/.bashrc"  # COODOOC bashrc
CODOCS["codoc"]="${HOME}/.local/scripts/codoc"  # COODOOC codoc
CODOCS["codocrc"]="${HOME}/.config/codocrc"  # COODOOC codocrc
CODOCS["sdiwctl"]="${HOME}/.local/scripts/sdiwctl"  # COODOOC sdiwctl
CODOCS["vimrc"]="${HOME}/.config/vim/vimrc"  # COODOOC vimrc

